export let objUser = [
  {
    dateTime: "2023-03-03 09:00:00",
    title: "Meeting with Client",
    description: "Discuss project requirements",
    location: "Hanoi, Vietnam",
    imgUrl: "https://example.com/images/client.png",
  },
  {
    dateTime: "2023-03-04 14:00:00",
    title: "Team Building Event",
    description: "Fun activities and games",
    location: "Ho Chi Minh City, Vietnam",
    imgUrl: "https://example.com/images/team-building.png",
  },
  {
    dateTime: "2023-03-05 10:30:00",
    title: "Product Demo",
    description: "Showcase new product features",
    location: "Singapore",
    imgUrl: "https://example.com/images/product.png",
  },
  {
    dateTime: "2023-03-06 11:00:00",
    title: "Interview",
    description: "Hiring for a new position",
    location: "Sydney, Australia",
    imgUrl: "https://example.com/images/interview.png",
  },
  {
    dateTime: "2023-03-07 15:00:00",
    title: "Webinar",
    description: "Learn about the latest industry trends",
    location: "Online",
    imgUrl: "https://example.com/images/webinar.png",
  },
  {
    dateTime: "2023-03-08 13:30:00",
    title: "Product Launch",
    description: "Introduce new product to market",
    location: "Tokyo, Japan",
    imgUrl: "https://example.com/images/product-launch.png",
  },
  {
    dateTime: "2023-03-09 09:30:00",
    title: "Conference",
    description: "Networking and educational sessions",
    location: "Bangkok, Thailand",
    imgUrl: "https://example.com/images/conference.png",
  },
  {
    dateTime: "2023-03-10 12:00:00",
    title: "Client Presentation",
    description: "Present project progress to client",
    location: "Manila, Philippines",
    imgUrl: "https://example.com/images/client-presentation.png",
  },
  {
    dateTime: "2023-03-11 16:00:00",
    title: "Business Trip",
    description: "Meet with partners and suppliers",
    location: "Shanghai, China",
    imgUrl: "https://example.com/images/business-trip.png",
  },
  {
    dateTime: "2023-03-12 11:30:00",
    title: "Training Session",
    description: "Learn new skills and techniques",
    location: "Seoul, South Korea",
    imgUrl: "https://example.com/images/training.png",
  },
];
